### ISSUE TITLE
detectei um problema

### ISSUE THREAD

**Issue by victalejo** [fexd12/bot-sinais#1]
Olá, excelente script, detectei um problema Depois de iniciar uma operação

C:\Users\inter\Downloads\bot-sinais-master\bot-sinais-master>main.py
 Conectado com sucesso!

Iniciando operação!
Paridade EURUSD-OTC opcao: digital / Horario: 22:15 / Direção: put
   ->  loss / 0

   MARTINGALE NIVEL 1..  win / 3.61

Iniciando operação!
Traceback (most recent call last):
  File "C:\Users\inter\Downloads\bot-sinais-master\bot-sinais-master\main.py", line 200, in <module>
    opcao = checkProfit(par,5)
  File "C:\Users\inter\Downloads\bot-sinais-master\bot-sinais-master\main.py", line 135, in checkProfit
    if profit_Binary_Real <  profit_Digital :
TypeError: '<' not supported between instances of 'dict' and 'float'

C:\Users\inter\Downloads\bot-sinais-master\bot-sinais-master>

**Comment by fexd12** [comment]
Poderia me informar o sinal que tu usou para acarretar esse erro, pois fazendo uns testes nao cheguei a esse erro.

**Comment by victalejo** [comment]
Vi que ele só lida com sinais na 5M e eu estava entrando em prazos diferentes; talvez tenha sido muito obrigado

**Comment by fexd12** [comment]
em breve vou colocar para outros timeframes tambem
