### ISSUE TITLE
erro com a lista

### ISSUE THREAD

**Issue by lukefeix** [fexd12/bot-sinais#2]
Olá Boa noite
esta dando esse erro depois que ele faz a primeira entrada, sabe o que pode ser?

![image](https://user-images.githubusercontent.com/67929862/86860947-4ac3d280-c09c-11ea-81ee-ab1f36b8953d.png)

**Comment by fexd12** [comment]
qual o fomato da lista que tu esta fornecendo ao bot?
pode ser que erro esteja na forma como ele esta fazendo o for.
vou testar com uma lista para ver

**Comment by lukefeix** [comment]
M5;EURUSD;00:50:00;call
M5;EURUSD;01:45:00;call
M5;EURUSD;02:20:00;call
M5;EURUSD;05:20:00;call
M5;EURUSD;09:35:00;call
M5;EURUSD;12:00:00;call


Estou fazendo como o modelo que você deixou...
ele pega somente a primeira entrada e da o erro

**Comment by lukefeix** [comment]
acho que descobri. como são horarios para amanhã ele da como se o horario já tivesse passado, sabe como fazer ele entender que é para o dia seguinte?

**Comment by fexd12** [comment]
na config.txt tu pode colocar um parametro para ver para qual dia é a lista, e na main.py tu verificar esse parametro.
tem uma funcao ja que é a timestamp converter, nela tu pode acrescentar para trazer a data tambem retornando uma tupla e verificar as data se batem.
